[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quilt-spreadsheet"
version = "0.1.0"
description = "The Quilt IDE as spreadsheet substrate"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["quilt_spreadsheet"]
